// src/lib/constants/validation.ts
export const TEXT_LIMITS = {
    MAX_WORD_LENGTH: 50,
    MAX_DEFINITION_LENGTH: 280,
    MAX_STATEMENT_LENGTH: 280,
    MAX_OPENQUESTION_LENGTH: 280,        
    MAX_COMMENT_LENGTH: 280,
    MAX_KEYWORD_LENGTH: 30,
    MAX_KEYWORDS: 10
} as const;